Add text length limit on TextBox control
billyquith/GWork pull request #51
Opened 2017-06-01 11:50 UTC by okonk

As per the discussion, went with an approach that once the limit is reached no more text can be entered. This seems to be the standard behaviour used by other applications and makes sense.

Can adjust naming/stuff if required.

2017-06-01 14:37 UTC, Grant1219 reviewed
I would prefer to use `size_t` when dealing with string lengths, but I realize `int` is being used here for the special case where there is no text limit and `m_maxTextLength` is set to `-1`.

2017-06-01 15:41 UTC, billyquith commented
> I would prefer to use `size_t` when dealing with string length
Fair comment, but `int` is used throughout the code. I have a ticket #45 to work on this.

2017-06-02 08:57 UTC, billyquith requested changes
Could you please make the changes suggested. I'm more keen on the demo that the change works, and return type.

2017-06-02 08:57 UTC, billyquith commented on source/gwork/include/Gwork/Controls/TextBox.h
> +            const int& GetMaxTextLength() const { return m_maxTextLength; }
We can return `int` here

2017-06-02 08:57 UTC, billyquith commented on source/gwork/source/Controls/TextBox.cpp
> +    m_maxTextLength = -1;
Be nice if `-1` wasn't a magic number. Perhaps `static constexpr NO_MAX_LENGTH = -1;` ?

2017-06-02 08:57 UTC, billyquith commented on source/test/source/api/TextBox.cpp
> +            label->SetMaxTextLength(20);
After this, perhaps you could set the text to something longer than the maximum length to test whether this works as expected?

2017-06-02 11:28 UTC, okonk commented
What happens is the text will be larger (since we're only checking the limit on insert), but nothing bad happens, the user just has to take the text below the limit before they can edit it. That seems alright to me. I'll add a test for it anyway

2017-06-02 12:00 UTC, billyquith commented
Yep, but I think you added another control, so just want to distinguish what the control is demonstrating. E.g. setText(...), setMaxTextLen(6), setText("Maximum text length"), so we can see that the length has been clamped/truncated, and that any editing maintains this. - possibly you could add a counter next to it showing the text length, but that is entirely optional.

2017-06-02 16:50 UTC, Grant1219 commented on source/gwork/include/Gwork/Controls/TextBox.h
> +            static constexpr int NO_MAX_LENGTH = -1;
This could just be `static const int NO_MAX_LENGTH = -1;`

2017-06-02 23:19 UTC, okonk commented
Alright, changed it to add an extra SetText after SetMaxTextLength

2017-06-03 09:37 UTC, billyquith commented on source/gwork/include/Gwork/Controls/TextBox.h
> +            static constexpr int NO_MAX_LENGTH = -1;
This project is C++11 so there is no reason not to use `constexpr`.

2017-06-03 09:41 UTC, billyquith commented on source/gwork/source/Controls/TextBox.cpp
> +    if (m_maxTextLength > NO_MAX_LENGTH && TextLength() + insertSize > m_maxTextLength)
This should be != NO_MAX_LENGTH as it is a magic number out of the usual range.

2017-06-03 09:41 UTC, billyquith approved these changes
Thanks for making the changes. I haven't tested them but look good.

2017-06-03 09:42 UTC, merged